# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "orisemporium"
client_id = "07024a60a4afa0197d846c2d610273dc"
application_url = "https://pharmaceutical-barrel-pub-deborah.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pharmaceutical-barrel-pub-deborah.trycloudflare.com/auth/callback",
  "https://pharmaceutical-barrel-pub-deborah.trycloudflare.com/auth/shopify/callback",
  "https://pharmaceutical-barrel-pub-deborah.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "oxavions-emporium.myshopify.com"
